### ISSUE TITLE
Explain your process

### ISSUE THREAD

**Issue by moermann** [dshean/nasadem#2]
Hi Mr. Shean,

may you please explain, why such a complicated process is necessary?
```
gdalbuildvrt ${site}_nasadem_${ext}.vrt $fn_list
gdaladdo_ro.sh ${site}_nasadem_${ext}.vrt
gdal_translate $gdal_opt ${site}_nasadem_${ext}.vrt ${site}_nasadem_${ext}.tif
gdalwarp -overwrite $gdal_opt -r cubic -t_srs "$proj" -tr 30 30 nasadem_${ext}.vrt nasadem_${ext}_30m.tif

#Should mask elevation values where err >= 32769
exit

gdalwarp -overwrite $gdal_opt -r cubic -t_srs "$proj" -tr 90 90 nasadem_${ext}.vrt nasadem_${ext}_90m.tif
hs.sh nasadem_${ext}_90m.tif
gdaladdo_ro.sh nasadem_${ext}_90m.tif
gdaladdo_ro.sh nasadem_${ext}_90m_hs_az315.tif
```

And may you please replace gdaladdo_ro.sh by gdaladdo -ro ?

**Comment by dshean** [comment]
Hi @moermann.  That script was used to generate a one-time mosaic of high-mountain Asia with an Albers Equal Area projection.  Please feel free to fork and modify for your own needs.  You could work directly with the vrt if desired.  I wanted a single output tif that I could distribute easily.  Everything after the `exit` command was from an earlier test.  

My `gdaladdo_ro.sh` script is a wrapper around `gdaladdo` that uses GNU parallel to process many files simultaneously: https://github.com/dshean/imview/blob/master/imview/gdaladdo_ro.sh.  Again, feel free to modify for your own needs.

**Comment by dshean** [comment]
OK, I finally had a chance to update this repo.  Fixed a bug in the header generation script (pixel center  vs. lower left corner issue) to remove systematic (-15, 15 m) offsets.  Cleaned up the tools, and tried to add more comments.
